# Generated by Django 4.2.7 on 2025-11-26 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentsession",
            name="paystack_reference",
            field=models.CharField(
                blank=True, default=django.utils.timezone.now, max_length=255
            ),
            preserve_default=False,
        ),
    ]
