# Generated by Django 5.2.7 on 2025-11-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_paymentsession_paystack_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("event", models.CharField(blank=True, max_length=128, null=True)),
                ("reference", models.CharField(blank=True, max_length=255, null=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("headers", models.JSONField(blank=True, null=True)),
                ("processed", models.BooleanField(default=False)),
                ("result", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
    ]
